// Countries data with flags (using emoji flags)
// ISO 3166-1 alpha-2 country codes

export interface Country {
  code: string
  flag: string
  nameEn: string
  nameRu: string
}

export const countries: Country[] = [
  { code: "US", flag: "🇺🇸", nameEn: "United States", nameRu: "Соединенные Штаты" },
  { code: "GB", flag: "🇬🇧", nameEn: "United Kingdom", nameRu: "Великобритания" },
  { code: "CA", flag: "🇨🇦", nameEn: "Canada", nameRu: "Канада" },
  { code: "AU", flag: "🇦🇺", nameEn: "Australia", nameRu: "Австралия" },
  { code: "DE", flag: "🇩🇪", nameEn: "Germany", nameRu: "Германия" },
  { code: "FR", flag: "🇫🇷", nameEn: "France", nameRu: "Франция" },
  { code: "IT", flag: "🇮🇹", nameEn: "Italy", nameRu: "Италия" },
  { code: "ES", flag: "🇪🇸", nameEn: "Spain", nameRu: "Испания" },
  { code: "NL", flag: "🇳🇱", nameEn: "Netherlands", nameRu: "Нидерланды" },
  { code: "BE", flag: "🇧🇪", nameEn: "Belgium", nameRu: "Бельгия" },
  { code: "CH", flag: "🇨🇭", nameEn: "Switzerland", nameRu: "Швейцария" },
  { code: "AT", flag: "🇦🇹", nameEn: "Austria", nameRu: "Австрия" },
  { code: "SE", flag: "🇸🇪", nameEn: "Sweden", nameRu: "Швеция" },
  { code: "NO", flag: "🇳🇴", nameEn: "Norway", nameRu: "Норвегия" },
  { code: "DK", flag: "🇩🇰", nameEn: "Denmark", nameRu: "Дания" },
  { code: "FI", flag: "🇫🇮", nameEn: "Finland", nameRu: "Финляндия" },
  { code: "PL", flag: "🇵🇱", nameEn: "Poland", nameRu: "Польша" },
  { code: "CZ", flag: "🇨🇿", nameEn: "Czech Republic", nameRu: "Чехия" },
  { code: "PT", flag: "🇵🇹", nameEn: "Portugal", nameRu: "Португалия" },
  { code: "IE", flag: "🇮🇪", nameEn: "Ireland", nameRu: "Ирландия" },
  { code: "GR", flag: "🇬🇷", nameEn: "Greece", nameRu: "Греция" },
  { code: "TR", flag: "🇹🇷", nameEn: "Turkey", nameRu: "Турция" },
  { code: "RU", flag: "🇷🇺", nameEn: "Russia", nameRu: "Россия" },
  { code: "CN", flag: "🇨🇳", nameEn: "China", nameRu: "Китай" },
  { code: "JP", flag: "🇯🇵", nameEn: "Japan", nameRu: "Япония" },
  { code: "KR", flag: "🇰🇷", nameEn: "South Korea", nameRu: "Южная Корея" },
  { code: "SG", flag: "🇸🇬", nameEn: "Singapore", nameRu: "Сингапур" },
  { code: "MY", flag: "🇲🇾", nameEn: "Malaysia", nameRu: "Малайзия" },
  { code: "TH", flag: "🇹🇭", nameEn: "Thailand", nameRu: "Таиланд" },
  { code: "IN", flag: "🇮🇳", nameEn: "India", nameRu: "Индия" },
  { code: "ID", flag: "🇮🇩", nameEn: "Indonesia", nameRu: "Индонезия" },
  { code: "PH", flag: "🇵🇭", nameEn: "Philippines", nameRu: "Филиппины" },
  { code: "VN", flag: "🇻🇳", nameEn: "Vietnam", nameRu: "Вьетнам" },
  { code: "NZ", flag: "🇳🇿", nameEn: "New Zealand", nameRu: "Новая Зеландия" },
  { code: "BR", flag: "🇧🇷", nameEn: "Brazil", nameRu: "Бразилия" },
  { code: "MX", flag: "🇲🇽", nameEn: "Mexico", nameRu: "Мексика" },
  { code: "AR", flag: "🇦🇷", nameEn: "Argentina", nameRu: "Аргентина" },
  { code: "CL", flag: "🇨🇱", nameEn: "Chile", nameRu: "Чили" },
  { code: "CO", flag: "🇨🇴", nameEn: "Colombia", nameRu: "Колумбия" },
  { code: "PE", flag: "🇵🇪", nameEn: "Peru", nameRu: "Перу" },
  { code: "ZA", flag: "🇿🇦", nameEn: "South Africa", nameRu: "Южная Африка" },
  { code: "EG", flag: "🇪🇬", nameEn: "Egypt", nameRu: "Египет" },
  { code: "AE", flag: "🇦🇪", nameEn: "United Arab Emirates", nameRu: "ОАЭ" },
  { code: "SA", flag: "🇸🇦", nameEn: "Saudi Arabia", nameRu: "Саудовская Аравия" },
  { code: "IL", flag: "🇮🇱", nameEn: "Israel", nameRu: "Израиль" },
  { code: "HU", flag: "🇭🇺", nameEn: "Hungary", nameRu: "Венгрия" },
  { code: "RO", flag: "🇷🇴", nameEn: "Romania", nameRu: "Румыния" },
  { code: "BG", flag: "🇧🇬", nameEn: "Bulgaria", nameRu: "Болгария" },
  { code: "HR", flag: "🇭🇷", nameEn: "Croatia", nameRu: "Хорватия" },
  { code: "SI", flag: "🇸🇮", nameEn: "Slovenia", nameRu: "Словения" },
  { code: "SK", flag: "🇸🇰", nameEn: "Slovakia", nameRu: "Словакия" },
  { code: "LT", flag: "🇱🇹", nameEn: "Lithuania", nameRu: "Литва" },
  { code: "LV", flag: "🇱🇻", nameEn: "Latvia", nameRu: "Латвия" },
  { code: "EE", flag: "🇪🇪", nameEn: "Estonia", nameRu: "Эстония" },
  { code: "IS", flag: "🇮🇸", nameEn: "Iceland", nameRu: "Исландия" },
  { code: "LU", flag: "🇱🇺", nameEn: "Luxembourg", nameRu: "Люксембург" },
  { code: "MT", flag: "🇲🇹", nameEn: "Malta", nameRu: "Мальта" },
  { code: "CY", flag: "🇨🇾", nameEn: "Cyprus", nameRu: "Кипр" },
  // Additional countries - Europe
  { code: "AD", flag: "🇦🇩", nameEn: "Andorra", nameRu: "Андорра" },
  { code: "AL", flag: "🇦🇱", nameEn: "Albania", nameRu: "Албания" },
  { code: "AM", flag: "🇦🇲", nameEn: "Armenia", nameRu: "Армения" },
  { code: "AZ", flag: "🇦🇿", nameEn: "Azerbaijan", nameRu: "Азербайджан" },
  { code: "BA", flag: "🇧🇦", nameEn: "Bosnia and Herzegovina", nameRu: "Босния и Герцеговина" },
  { code: "BY", flag: "🇧🇾", nameEn: "Belarus", nameRu: "Беларусь" },
  { code: "FO", flag: "🇫🇴", nameEn: "Faroe Islands", nameRu: "Фарерские острова" },
  { code: "GE", flag: "🇬🇪", nameEn: "Georgia", nameRu: "Грузия" },
  { code: "GG", flag: "🇬🇬", nameEn: "Guernsey", nameRu: "Гернси" },
  { code: "GI", flag: "🇬🇮", nameEn: "Gibraltar", nameRu: "Гибралтар" },
  { code: "GL", flag: "🇬🇱", nameEn: "Greenland", nameRu: "Гренландия" },
  { code: "IM", flag: "🇮🇲", nameEn: "Isle of Man", nameRu: "Остров Мэн" },
  { code: "JE", flag: "🇯🇪", nameEn: "Jersey", nameRu: "Джерси" },
  { code: "LI", flag: "🇱🇮", nameEn: "Liechtenstein", nameRu: "Лихтенштейн" },
  { code: "MC", flag: "🇲🇨", nameEn: "Monaco", nameRu: "Монако" },
  { code: "MD", flag: "🇲🇩", nameEn: "Moldova", nameRu: "Молдова" },
  { code: "ME", flag: "🇲🇪", nameEn: "Montenegro", nameRu: "Черногория" },
  { code: "MK", flag: "🇲🇰", nameEn: "North Macedonia", nameRu: "Северная Македония" },
  { code: "RS", flag: "🇷🇸", nameEn: "Serbia", nameRu: "Сербия" },
  { code: "SM", flag: "🇸🇲", nameEn: "San Marino", nameRu: "Сан-Марино" },
  { code: "UA", flag: "🇺🇦", nameEn: "Ukraine", nameRu: "Украина" },
  { code: "VA", flag: "🇻🇦", nameEn: "Vatican City", nameRu: "Ватикан" },
  // Additional countries - Asia
  { code: "AF", flag: "🇦🇫", nameEn: "Afghanistan", nameRu: "Афганистан" },
  { code: "BD", flag: "🇧🇩", nameEn: "Bangladesh", nameRu: "Бангладеш" },
  { code: "BH", flag: "🇧🇭", nameEn: "Bahrain", nameRu: "Бахрейн" },
  { code: "BN", flag: "🇧🇳", nameEn: "Brunei", nameRu: "Бруней" },
  { code: "BT", flag: "🇧🇹", nameEn: "Bhutan", nameRu: "Бутан" },
  { code: "HK", flag: "🇭🇰", nameEn: "Hong Kong", nameRu: "Гонконг" },
  { code: "IQ", flag: "🇮🇶", nameEn: "Iraq", nameRu: "Ирак" },
  { code: "IR", flag: "🇮🇷", nameEn: "Iran", nameRu: "Иран" },
  { code: "JO", flag: "🇯🇴", nameEn: "Jordan", nameRu: "Иордания" },
  { code: "KZ", flag: "🇰🇿", nameEn: "Kazakhstan", nameRu: "Казахстан" },
  { code: "KG", flag: "🇰🇬", nameEn: "Kyrgyzstan", nameRu: "Кыргызстан" },
  { code: "KW", flag: "🇰🇼", nameEn: "Kuwait", nameRu: "Кувейт" },
  { code: "LA", flag: "🇱🇦", nameEn: "Laos", nameRu: "Лаос" },
  { code: "LB", flag: "🇱🇧", nameEn: "Lebanon", nameRu: "Ливан" },
  { code: "LK", flag: "🇱🇰", nameEn: "Sri Lanka", nameRu: "Шри-Ланка" },
  { code: "MM", flag: "🇲🇲", nameEn: "Myanmar", nameRu: "Мьянма" },
  { code: "MN", flag: "🇲🇳", nameEn: "Mongolia", nameRu: "Монголия" },
  { code: "MO", flag: "🇲🇴", nameEn: "Macao", nameRu: "Макао" },
  { code: "MV", flag: "🇲🇻", nameEn: "Maldives", nameRu: "Мальдивы" },
  { code: "NP", flag: "🇳🇵", nameEn: "Nepal", nameRu: "Непал" },
  { code: "OM", flag: "🇴🇲", nameEn: "Oman", nameRu: "Оман" },
  { code: "PK", flag: "🇵🇰", nameEn: "Pakistan", nameRu: "Пакистан" },
  { code: "PS", flag: "🇵🇸", nameEn: "Palestine", nameRu: "Палестина" },
  { code: "QA", flag: "🇶🇦", nameEn: "Qatar", nameRu: "Катар" },
  { code: "TW", flag: "🇹🇼", nameEn: "Taiwan", nameRu: "Тайвань" },
  { code: "TJ", flag: "🇹🇯", nameEn: "Tajikistan", nameRu: "Таджикистан" },
  { code: "TM", flag: "🇹🇲", nameEn: "Turkmenistan", nameRu: "Туркменистан" },
  { code: "UZ", flag: "🇺🇿", nameEn: "Uzbekistan", nameRu: "Узбекистан" },
  { code: "YE", flag: "🇾🇪", nameEn: "Yemen", nameRu: "Йемен" },
  // Additional countries - Africa
  { code: "AO", flag: "🇦🇴", nameEn: "Angola", nameRu: "Ангола" },
  { code: "BF", flag: "🇧🇫", nameEn: "Burkina Faso", nameRu: "Буркина-Фасо" },
  { code: "BI", flag: "🇧🇮", nameEn: "Burundi", nameRu: "Бурунди" },
  { code: "BJ", flag: "🇧🇯", nameEn: "Benin", nameRu: "Бенин" },
  { code: "BW", flag: "🇧🇼", nameEn: "Botswana", nameRu: "Ботсвана" },
  { code: "CD", flag: "🇨🇩", nameEn: "DR Congo", nameRu: "ДР Конго" },
  { code: "CF", flag: "🇨🇫", nameEn: "Central African Republic", nameRu: "ЦАР" },
  { code: "CG", flag: "🇨🇬", nameEn: "Congo", nameRu: "Конго" },
  { code: "CI", flag: "🇨🇮", nameEn: "Ivory Coast", nameRu: "Кот-д'Ивуар" },
  { code: "CM", flag: "🇨🇲", nameEn: "Cameroon", nameRu: "Камерун" },
  { code: "CV", flag: "🇨🇻", nameEn: "Cape Verde", nameRu: "Кабо-Верде" },
  { code: "DJ", flag: "🇩🇯", nameEn: "Djibouti", nameRu: "Джибути" },
  { code: "DZ", flag: "🇩🇿", nameEn: "Algeria", nameRu: "Алжир" },
  { code: "EH", flag: "🇪🇭", nameEn: "Western Sahara", nameRu: "Западная Сахара" },
  { code: "ER", flag: "🇪🇷", nameEn: "Eritrea", nameRu: "Эритрея" },
  { code: "ET", flag: "🇪🇹", nameEn: "Ethiopia", nameRu: "Эфиопия" },
  { code: "GA", flag: "🇬🇦", nameEn: "Gabon", nameRu: "Габон" },
  { code: "GH", flag: "🇬🇭", nameEn: "Ghana", nameRu: "Гана" },
  { code: "GM", flag: "🇬🇲", nameEn: "Gambia", nameRu: "Гамбия" },
  { code: "GN", flag: "🇬🇳", nameEn: "Guinea", nameRu: "Гвинея" },
  { code: "GW", flag: "🇬🇼", nameEn: "Guinea-Bissau", nameRu: "Гвинея-Бисау" },
  { code: "KE", flag: "🇰🇪", nameEn: "Kenya", nameRu: "Кения" },
  { code: "KM", flag: "🇰🇲", nameEn: "Comoros", nameRu: "Коморы" },
  { code: "LR", flag: "🇱🇷", nameEn: "Liberia", nameRu: "Либерия" },
  { code: "LS", flag: "🇱🇸", nameEn: "Lesotho", nameRu: "Лесото" },
  { code: "LY", flag: "🇱🇾", nameEn: "Libya", nameRu: "Ливия" },
  { code: "MA", flag: "🇲🇦", nameEn: "Morocco", nameRu: "Марокко" },
  { code: "MG", flag: "🇲🇬", nameEn: "Madagascar", nameRu: "Мадагаскар" },
  { code: "ML", flag: "🇲🇱", nameEn: "Mali", nameRu: "Мали" },
  { code: "MR", flag: "🇲🇷", nameEn: "Mauritania", nameRu: "Мавритания" },
  { code: "MU", flag: "🇲🇺", nameEn: "Mauritius", nameRu: "Маврикий" },
  { code: "MW", flag: "🇲🇼", nameEn: "Malawi", nameRu: "Малави" },
  { code: "MZ", flag: "🇲🇿", nameEn: "Mozambique", nameRu: "Мозамбик" },
  { code: "NA", flag: "🇳🇦", nameEn: "Namibia", nameRu: "Намибия" },
  { code: "NE", flag: "🇳🇪", nameEn: "Niger", nameRu: "Нигер" },
  { code: "NG", flag: "🇳🇬", nameEn: "Nigeria", nameRu: "Нигерия" },
  { code: "RW", flag: "🇷🇼", nameEn: "Rwanda", nameRu: "Руанда" },
  { code: "SC", flag: "🇸🇨", nameEn: "Seychelles", nameRu: "Сейшелы" },
  { code: "SD", flag: "🇸🇩", nameEn: "Sudan", nameRu: "Судан" },
  { code: "SL", flag: "🇸🇱", nameEn: "Sierra Leone", nameRu: "Сьерра-Леоне" },
  { code: "SN", flag: "🇸🇳", nameEn: "Senegal", nameRu: "Сенегал" },
  { code: "SO", flag: "🇸🇴", nameEn: "Somalia", nameRu: "Сомали" },
  { code: "SS", flag: "🇸🇸", nameEn: "South Sudan", nameRu: "Южный Судан" },
  { code: "SZ", flag: "🇸🇿", nameEn: "Eswatini", nameRu: "Эсватини" },
  { code: "TD", flag: "🇹🇩", nameEn: "Chad", nameRu: "Чад" },
  { code: "TG", flag: "🇹🇬", nameEn: "Togo", nameRu: "Того" },
  { code: "TN", flag: "🇹🇳", nameEn: "Tunisia", nameRu: "Тунис" },
  { code: "TZ", flag: "🇹🇿", nameEn: "Tanzania", nameRu: "Танзания" },
  { code: "UG", flag: "🇺🇬", nameEn: "Uganda", nameRu: "Уганда" },
  { code: "ZM", flag: "🇿🇲", nameEn: "Zambia", nameRu: "Замбия" },
  { code: "ZW", flag: "🇿🇼", nameEn: "Zimbabwe", nameRu: "Зимбабве" },
  // Additional countries - Americas
  { code: "AG", flag: "🇦🇬", nameEn: "Antigua and Barbuda", nameRu: "Антигуа и Барбуда" },
  { code: "AI", flag: "🇦🇮", nameEn: "Anguilla", nameRu: "Ангилья" },
  { code: "AW", flag: "🇦🇼", nameEn: "Aruba", nameRu: "Аруба" },
  { code: "BB", flag: "🇧🇧", nameEn: "Barbados", nameRu: "Барбадос" },
  { code: "BZ", flag: "🇧🇿", nameEn: "Belize", nameRu: "Белиз" },
  { code: "BO", flag: "🇧🇴", nameEn: "Bolivia", nameRu: "Боливия" },
  { code: "BS", flag: "🇧🇸", nameEn: "Bahamas", nameRu: "Багамы" },
  { code: "CR", flag: "🇨🇷", nameEn: "Costa Rica", nameRu: "Коста-Рика" },
  { code: "CU", flag: "🇨🇺", nameEn: "Cuba", nameRu: "Куба" },
  { code: "DM", flag: "🇩🇲", nameEn: "Dominica", nameRu: "Доминика" },
  { code: "DO", flag: "🇩🇴", nameEn: "Dominican Republic", nameRu: "Доминиканская Республика" },
  { code: "EC", flag: "🇪🇨", nameEn: "Ecuador", nameRu: "Эквадор" },
  { code: "GD", flag: "🇬🇩", nameEn: "Grenada", nameRu: "Гренада" },
  { code: "GT", flag: "🇬🇹", nameEn: "Guatemala", nameRu: "Гватемала" },
  { code: "GY", flag: "🇬🇾", nameEn: "Guyana", nameRu: "Гайана" },
  { code: "HN", flag: "🇭🇳", nameEn: "Honduras", nameRu: "Гондурас" },
  { code: "HT", flag: "🇭🇹", nameEn: "Haiti", nameRu: "Гаити" },
  { code: "JM", flag: "🇯🇲", nameEn: "Jamaica", nameRu: "Ямайка" },
  { code: "KN", flag: "🇰🇳", nameEn: "Saint Kitts and Nevis", nameRu: "Сент-Китс и Невис" },
  { code: "KY", flag: "🇰🇾", nameEn: "Cayman Islands", nameRu: "Каймановы острова" },
  { code: "LC", flag: "🇱🇨", nameEn: "Saint Lucia", nameRu: "Сент-Люсия" },
  { code: "PA", flag: "🇵🇦", nameEn: "Panama", nameRu: "Панама" },
  { code: "PY", flag: "🇵🇾", nameEn: "Paraguay", nameRu: "Парагвай" },
  { code: "SR", flag: "🇸🇷", nameEn: "Suriname", nameRu: "Суринам" },
  { code: "SV", flag: "🇸🇻", nameEn: "El Salvador", nameRu: "Сальвадор" },
  { code: "TT", flag: "🇹🇹", nameEn: "Trinidad and Tobago", nameRu: "Тринидад и Тобаго" },
  { code: "UY", flag: "🇺🇾", nameEn: "Uruguay", nameRu: "Уругвай" },
  { code: "VC", flag: "🇻🇨", nameEn: "Saint Vincent and the Grenadines", nameRu: "Сент-Винсент и Гренадины" },
  { code: "VE", flag: "🇻🇪", nameEn: "Venezuela", nameRu: "Венесуэла" },
  // Additional countries - Oceania
  { code: "AS", flag: "🇦🇸", nameEn: "American Samoa", nameRu: "Американское Самоа" },
  { code: "CK", flag: "🇨🇰", nameEn: "Cook Islands", nameRu: "Острова Кука" },
  { code: "FJ", flag: "🇫🇯", nameEn: "Fiji", nameRu: "Фиджи" },
  { code: "FM", flag: "🇫🇲", nameEn: "Micronesia", nameRu: "Микронезия" },
  { code: "GU", flag: "🇬🇺", nameEn: "Guam", nameRu: "Гуам" },
  { code: "KI", flag: "🇰🇮", nameEn: "Kiribati", nameRu: "Кирибати" },
  { code: "MH", flag: "🇲🇭", nameEn: "Marshall Islands", nameRu: "Маршалловы Острова" },
  { code: "MP", flag: "🇲🇵", nameEn: "Northern Mariana Islands", nameRu: "Северные Марианские острова" },
  { code: "NC", flag: "🇳🇨", nameEn: "New Caledonia", nameRu: "Новая Каледония" },
  { code: "NR", flag: "🇳🇷", nameEn: "Nauru", nameRu: "Науру" },
  { code: "NU", flag: "🇳🇺", nameEn: "Niue", nameRu: "Ниуэ" },
  { code: "PF", flag: "🇵🇫", nameEn: "French Polynesia", nameRu: "Французская Полинезия" },
  { code: "PG", flag: "🇵🇬", nameEn: "Papua New Guinea", nameRu: "Папуа-Новая Гвинея" },
  { code: "PW", flag: "🇵🇼", nameEn: "Palau", nameRu: "Палау" },
  { code: "SB", flag: "🇸🇧", nameEn: "Solomon Islands", nameRu: "Соломоновы Острова" },
  { code: "TO", flag: "🇹🇴", nameEn: "Tonga", nameRu: "Тонга" },
  { code: "TV", flag: "🇹🇻", nameEn: "Tuvalu", nameRu: "Тувалу" },
  { code: "VU", flag: "🇻🇺", nameEn: "Vanuatu", nameRu: "Вануату" },
  { code: "WS", flag: "🇼🇸", nameEn: "Samoa", nameRu: "Самоа" },
]

// Helper function to get country by code
export function getCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code === code)
}

// Helper function to get country name based on language
export function getCountryName(country: Country, language: "en" | "ru"): string {
  return language === "ru" ? country.nameRu : country.nameEn
}

// Helper function to get sorted countries (by name in current language)
export function getSortedCountries(language: "en" | "ru"): Country[] {
  return [...countries].sort((a, b) => {
    const nameA = getCountryName(a, language).toLowerCase()
    const nameB = getCountryName(b, language).toLowerCase()
    return nameA.localeCompare(nameB)
  })
}
